name: imaginator
description: Image Viewer
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  file_selector: ^1.0.3
  file_selector_linux: ^0.9.2+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.1
  integration_test:
    sdk: flutter
  photo_view: ^0.14.0
  provider: ^6.1.1
  safe_change_notifier: ^0.3.2
  yaru: ^1.2.2
  yaru_icons: ^2.4.0
  yaru_widgets: ^3.6.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
