name: imaginator
version: git
summary: imaginator
description: Image Viewer
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  imaginator:
    plugin: flutter
    source: .

apps:
  imaginator:
    command: imaginator
    desktop: data/flutter_assets/assets/imaginator.desktop
    extensions: [gnome]
